### ISSUE TITLE
Suggestion: more verbose output

### ISSUE THREAD

**Issue by danihek** [Danrus1100/walcord#3]
As title says, more verbose program to actually know what's happening, maybe that's me but I was confused while trying to make it work for couple of minutes without confirmation like: theme applied [ image path]etc. or something. 

Also with this also addtional argument comes in: -q, --quiet if you dont want any output.

**Comment by Danrus1100** [comment]
Thanks for the suggestion. It gave me a couple more ideas of what I could add to the script. I'll get on it today...

**Comment by Danrus1100** [comment]
I've added the suggested changes. thanks again for the suggestion and help!
